drop testing for Faraday 0 under Ruby 2.2
faraday 0.x depends on multipart-post.

multipart-post v2.2.0 started using a method deprecate_constant added
in Ruby 2.3.

Trying to use both results in the following error:

    Failure/Error: require "faraday"

    NoMethodError:
      undefined method `deprecate_constant' for Object:Class
    # /usr/local/bundle/gems/multipart-post-2.2.0/lib/multipart/post/parts.rb:152:in `<top (required)>'
    # /usr/local/bundle/gems/multipart-post-2.2.0/lib/multipart/post/multipartable.rb:23:in `require_relative'
    # /usr/local/bundle/gems/multipart-post-2.2.0/lib/multipart/post/multipartable.rb:23:in `<top (required)>'
    # /usr/local/bundle/gems/multipart-post-2.2.0/lib/multipart/post.rb:23:in `require_relative'
    # /usr/local/bundle/gems/multipart-post-2.2.0/lib/multipart/post.rb:23:in `<top (required)>'
    # /usr/local/bundle/gems/multipart-post-2.2.0/lib/composite_io.rb:2:in `require_relative'
    # /usr/local/bundle/gems/multipart-post-2.2.0/lib/composite_io.rb:2:in `<top (required)>'
    # /usr/local/bundle/gems/faraday-0.17.5/lib/faraday/upload_io.rb:2:in `require'

Old faraday and old Ruby is not something we want to try to account for
in our test suite. Users of this library who are on both can resolve
this error by pinning to working versions of multipart-post (~> 2.1.1).